### ISSUE TITLE
diff = ord(self.current[c - 1 - common]) - ord(w.s[i2]) -> IndexError: string index out of range

### ISSUE THREAD

**Issue by JustAnotherVeryNormalDeveloper** [snowballstem/snowball#201] opened 2024-10-02 09:54 UTC
Traceback:
```
File "/usr/local/lib/python3.9/site-packages/snowballstemmer/basestemmer.py", line 319, in stemWord\n    self._stem()\n
File "/usr/local/lib/python3.9/site-packages/snowballstemmer/french_stemmer.py", line 864, in _stem\n    if not self.__r_standard_suffix():\n
File "/usr/local/lib/python3.9/site-packages/snowballstemmer/french_stemmer.py", line 406, in __r_standard_suffix\n    among_var = self.find_among_b(FrenchStemmer.a_4)\n
File "/usr/local/lib/python3.9/site-packages/snowballstemmer/basestemmer.py", line 220, in find_among_b\n    diff = ord(self.current[c - 1 - common]) - ord(w.s[i2])\n', 'IndexError: string index out of range\n
```
I don't know if it's self.current or w.s that crash with the out of range.

I don't know why it arrives, sometime, the same call crash, depending on precedent calls or other changing states that I'm not aware of I suppose.

A solution can be a check before to see if the list has the right length.
Question is: in the if, we have to do diff = ? (i don't know which value should have diff if there is a out of range error, -1 ?)

Should we do a PR for this ?

**Comment by ojwb** [comment] 2024-10-02 21:09
> I don't know why it arrives, sometime, the same call crash, depending on precedent calls or other changing states that I'm not aware of I suppose.

The stemmers should behave predictably - the same input should produce the same output.  My best guess is you're calling the same stemmer object from more than one thread concurrently, which is explicitly not supported - `doc/libstemmer_python_README` says:

> The stemmer code is re-entrant, but not thread-safe if the same stemmer object is used concurrently in different threads.
>
> If you want to perform stemming concurrently in different threads, we suggest creating a new stemmer object for each thread.  The alternative is to share stemmer objects between threads and protect access using a mutex or similar (e.g. `threading.Lock` in Python) but that's liable to slow your program down as threads can end up waiting for the lock.

If that's not the cause, are you able to come up with a reproducer?

Just adding a check for this doesn't seem like it helps - the stemmer should behave predictably, but at this point we have inconsistent internal state.  An exception seems a reasonable response to this.

**Comment by ojwb** [comment] 2024-10-11 03:42
No feedback so closing as this to be due to incorrect use.

If you aren't using the same stemmer object concurrently from more than one thread please provide a reproducer and we can reopen and investigate.

**Closed by ojwb** 2024-10-11 03:42 UTC
