### ISSUE TITLE
create release tag

### ISSUE THREAD

**Issue by ncopa** [snowballstem/snowball#7] opened 2014-09-29 06:32 UTC
Hi,

It would be very helpful for packagers if you created release tags.

https://help.github.com/articles/about-releases

Thanks!

**Comment by ojwb** [comment] 2015-01-27 01:57
Every single release made from git has been tagged - the issue is really that no releases have been made from git yet rather than that we aren't tagging releases.

Prior to the move to git, Martin and RIchard weren't making explicitly versioned releases - you just got a tarball without a version number from http://snowball.tartarus.org/download.php - so there aren't any historic version numbers to add tags for either.

You could regard the SVN revision numbers as a versioning, but those aren't noted in the tarballs available from the URL above, and are noted in the git commit messages should you really want to know them - e.g. this corresponds to SVN rev 585:

```
commit 4bcae97db044253ea2edae1dd3ca59f3cddd4b9d
Author: Richard Boulton <richard@tartarus.org>
Date:   Tue Sep 2 10:06:14 2014 +0000

    The Hungarian stemmer should be ISO-8859-2 not -1
    
    As reported by Tom Lane on snowball-discuss.  Fix from Olly Betts.
    
    This commit includes the changes from
    https://github.com/snowballstem/snowball/pull/4 and from
    https://github.com/snowballstem/snowball-data/pull/2
    
    
    git-svn-id: svn+userv://snowball.tartarus.org/snowball/trunk/snowball@585 633ccae0-01f4-0310-8c99-d3591da6f01f
```

I'd really like to resolve the licensing before making a release from git.

**Comment by mikemcquaid** [comment] 2015-01-27 08:08
That's fair enough, thanks @ojwb. I may have understood but would there be any chance of pushing the existing tags into the Git repository? Thanks!

**Comment by ojwb** [comment] 2015-09-03 01:33
@mikemcquaid Sorry, I missed the question in that comment before.  As I tried to explain above, I don't think there are any existing tags, or anything that can be used to create tags.

We could perhaps tag the git commit corresponding to the "final" tarballs available from http://snowball.tartarus.org/download.php ("final" in the sense that the old site is now officially frozen - there will be releases from http://snowballstem.org/ starting in the (hopefully) near future).  If someone thinks that's useful to have a tag for, please figure out the hash of the corresponding commit and I'll be happy to add a tag for it.

**Comment by mikemcquaid** [comment] 2015-09-06 11:49
@ojwb I'm afraid I've no idea how I'd do that. That's ok though; if there will be tags for future releases that's :+1: from me.

**Comment by ojwb** [comment] 2015-10-14 22:37
@mikemcquaid Something like `git checkout <hash>` for each git commit in the timeline leading up to the date of those tarballs, and then diff the result against the tree from unpacking those tarballs until you find a match.  If there's an automatic way to do this with git, I'm not aware of it (but would love to know about it).

**Comment by mikemcquaid** [comment] 2015-10-15 07:32
That's a bit too involved for me personally but someone else may want to give it a go.

**Comment by mitya57** [comment] 2016-01-08 20:15
Hi Olly,
Is there any update on the new release? Do you have a list of remaining blockers somewhere?

**Comment by hydrapolic** [comment] 2017-12-23 02:59
Any update on this please?

**Comment by ojwb** [comment] 2019-10-02 04:07
We now have a release, complete with a tag:

https://github.com/snowballstem/snowball/releases/tag/v2.0.0

Closing.

**Closed by ojwb** 2019-10-02 04:07 UTC
