### ISSUE TITLE
Add stemmer generators for C# code

### ISSUE THREAD

**Issue by cesarsouza** [snowballstem/snowball#16] opened 2015-01-09 20:25 UTC
Hi there,

I would like to know if anyone is interested on having support for C# generators in this project. Generating C# code is actually quite different from what the Java generator does, as those languages, albeit similar, don't have the same constructs (i.e. labelled breaks/loops). As such, in order to create a generator for C#, it would be necessary to mix parts from the C/C++ generator and the Java one. Plus, it would also be interesting to have a .NET library for Snowball, in the same spirit as the Java one that is available in this repository.

As such, I just wanted to add that I have started a new fork to address those issues that is almost completely finished, with support for a new [generator_csharp.c](https://github.com/cesarsouza/snowball/blob/csharp-development/compiler/generator_csharp.c) that can already generate all stemmer definition files that come with Snowball. The generated C# files could be seen, for example, here:

 - https://github.com/cesarsouza/snowball/tree/csharp-development/csharp/Snowball/Algorithms

I have also added some unit tests for some languages, though not all of them yet. So, if any project maintainer would like this feature, I can send a pull request to merge my fork'd version. Otherwise I can just keep my fork around for anyone else that could be interested.

The fork is currently available at [https://github.com/cesarsouza/snowball](https://github.com/cesarsouza/snowball). In order to generate C# files, you can pass "-cs" to the command line compiler, as in

 - snowball.exe stem_ISO_8859_1.sbl -cs -o EnglishStemmer -name EnglishStemmer -u   

An [example generated file can be found here](https://github.com/cesarsouza/snowball/blob/csharp-development/csharp/Snowball/Algorithms/EnglishStemmer.generated.cs).

Hope it can be useful! :smiley:

**Comment by ojwb** [comment] 2015-01-12 01:10
I'm happy to merge support for other languages.

I think it would be good to have the results automatically tested for all the supported stemmers first though - I don't really know enough C# to useful maintain code written in it, so being able to spot if a change causes regressions there would be particularly useful.

**Comment by cesarsouza** [comment] 2015-01-21 19:28
Hi there,

Thanks for the response! 

In this case, I have added automatic tests against all languages in the snowball-data repository and added [Windows](https://github.com/cesarsouza/snowball/blob/csharp-development/csharp/generate.bat) and [Linux/Bash](https://github.com/cesarsouza/snowball/blob/csharp-development/csharp/generate.sh) scripts to generate language-specific C# files to included in the C# tool, as well as [Bash scripts to compile, run and test the generated program](https://github.com/cesarsouza/snowball/blob/csharp-development/csharp/build-mono.sh) on Linux using Mono. Those scripts could also be integrated in Travis as well, though I haven't done that yet.

Thus said, for the time being, there is only one single language whose generated output doesn't fully match its reference output in the snowball-data package: the [German2](https://github.com/cesarsouza/snowball/blob/csharp-development/algorithms/german2/stem_ISO_8859_1.sbl). I noticed that this particular language definition had been updated in the past to include a fix for -nisse terminated words. However, I found [a discussion from years ago that might indicate that fix hadn't been reflected in the reference data](http://comments.gmane.org/gmane.comp.search.snowball/1119) contained in the snowball-data repository. 

As such, please, may I ask if this is indeed the case, and if is thus safe to ignore this particular failing test?

Best regards,
Cesar

**Comment by ojwb** [comment] 2015-09-04 02:22
Yes, it looks like nobody actually heeded my request from way back then.  I've corrected this in 904339f60508de847363a7b9dbf24b0d28f209b4 (accidentally lumped in with an unrelated change to the data files), so if you merge the latest changes your tests should now pass.

I'm trying to catch up on the backlog of snowball stuff - could you prepare a pull request for this?

Also I'm trying to tidy up the licensing situation for snowball (see snowballstem/snowball#10 for more details).

So could you please confirm that you're OK to license these changes under the 3-clause BSD licence shown here:

http://opensource.org/licenses/BSD-3-Clause

**Comment by ojwb** [comment] 2015-09-04 04:24
Oh sorry, I see you already opened PR #17.  I'll close this issue and we can continue in the PR.

**Closed by ojwb** 2015-09-04 04:24 UTC
