### ISSUE TITLE
German - gender neutral language

### ISSUE THREAD

**Issue by eest9** [snowballstem/snowball#153] opened 2021-07-14 20:57 UTC
It appears that this dictionary for stemming doesn't deal properly with gender neutral word forms. In German often Texts use for example "Arbeiter*innen", "Arbeiter:innen" or "Arbeiter_innen" (aka gender gap) in order to include persons of all genders while most conservative authors just use "Arbeiter" (aka generic masculine). In my understanding this word forms should all be reduced to the same stem.

**Comment by ojwb** [comment] 2021-10-06 05:42
I worked out why the demo wasn't working (we need to specify the `u` flag so the regexp works on Unicode characters) and now it works as intended:

https://snowballstem.org/demo.html?text=Arbeiter*innen%0aArbeiter%23innen%0aArbeiter_innen#German

More generally though `_` might be a word character (as I noted above).

**Comment by ojwb** [comment] 2022-11-09 03:51
Closing - as I explained above, such cases will usually actually already work, and the submitter hasn't responded for over a year so I can only assume they were satisfied with that.

**Closed by ojwb** 2022-11-09 03:51 UTC
